"""first

Revision ID: 288f1bd3babf
Revises: 9384bcb0710e
Create Date: 2023-08-07 19:09:40.464877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288f1bd3babf'
down_revision = '9384bcb0710e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
