"""first1

Revision ID: e6d749195c3a
Revises: 288f1bd3babf
Create Date: 2023-08-07 21:56:55.996263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d749195c3a'
down_revision = '288f1bd3babf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
